App/urls.py
from django.conf.urls import url

from App import views

urlpatterns = [
    url(r'^home/', views.home, name='home'),
    url(r'^market/', views.market, name='market'),
    url(r'^marketwithparams/(?P<typeid>\d+)/(?P<childcid>\d+)/(?P<order_rule>\d+)/', views.market_with_params,
        name='market_with_params'),
    url(r'^cart/', views.cart, name='cart'),
    url(r'^mine/', views.mine, name='mine'),

    url(r'^register/', views.register, name='register'),
    url(r'^login/', views.login, name='login'),
    url(r'^checkuser/', views.check_user, name='check_user'),

    url(r'^logout/', views.logout, name='logout'),
    url(r'^activate/', views.activate, name='activate'),
    url(r'^addtocart/', views.add_to_cart, name='add_to_cart'),
    url(r'^changecartstate/', views.change_cart_state, name='change_cart_state'),
    url(r'^subshopping/', views.sub_shopping, name='sub_shopping'),
    url(r'^allselect/', views.all_select, name='all_select'),
    url(r'^makeorder/', views.make_order, name='make_order'),
    url(r'^orderdetail/', views.order_detail, name='order_detail'),
    url(r'^orderlistnotpay/', views.order_list_not_pay, name='order_list_not_pay'),
    url(r'^payed/', views.payed, name='payed'),
    url(r'^alipay/', views.alipay, name='alipay'),
]

newpro/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from newpro import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('App.urls', namespace='axf')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

App/models.py
from django.db import models

from App.views_constant import ORDER_STATUS_NOT_PAY


class Main(models.Model):
    img = models.CharField(max_length=255)
    name = models.CharField(max_length=64)
    trackid = models.IntegerField(default=1)

    class Meta:
        abstract = True


class MainWheel(Main):
    class Meta:
        db_table = 'axf_wheel'


class MainNav(Main):
    class Meta:
        db_table = 'axf_nav'


class MainMustBuy(Main):
    class Meta:
        db_table = 'axf_mustbuy'


class MainShop(Main):
    class Meta:
        db_table = 'axf_shop'


class MainShow(Main):
    categoryid = models.IntegerField(default=1)
    brandname = models.CharField(max_length=64)
    img1 = models.CharField(max_length=255)
    childcid1 = models.IntegerField(default=1)
    productid1 = models.IntegerField(default=1)
    longname1 = models.CharField(max_length=128)
    price1 = models.FloatField(default=1)
    marketprice1 = models.FloatField(default=0)
    img2 = models.CharField(max_length=255)
    childcid2 = models.IntegerField(default=1)
    productid2 = models.IntegerField(default=1)
    longname2 = models.CharField(max_length=128)
    price2 = models.FloatField(default=1)
    marketprice2 = models.FloatField(default=0)
    img3 = models.CharField(max_length=255)
    childcid3 = models.IntegerField(default=1)
    productid3 = models.IntegerField(default=1)
    longname3 = models.CharField(max_length=128)
    price3 = models.FloatField(default=1)
    marketprice3 = models.FloatField(default=0)

    class Meta:
        db_table = 'axf_mainshow'


class FoodType(models.Model):
    typeid = models.IntegerField(default=1)
    typename = models.CharField(max_length=32)
    childtypenames = models.CharField(max_length=255)
    typesort = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_foodtype'


class Goods(models.Model):
    productid = models.IntegerField(default=1)
    productimg = models.CharField(max_length=255)
    productname = models.CharField(max_length=128)
    productlongname = models.CharField(max_length=255)
    isxf = models.BooleanField(default=False)
    pmdesc = models.BooleanField(default=False)
    specifics = models.CharField(max_length=64)
    price = models.FloatField(default=0)
    marketprice = models.FloatField(default=1)
    categoryid = models.IntegerField(default=1)
    childcid = models.IntegerField(default=1)
    childname = models.CharField(max_length=128)
    dealerid = models.IntegerField(default=1)
    storenums = models.IntegerField(default=1)
    productnum = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_goods'


class AXFUser(models.Model):
    u_username = models.CharField(max_length=32, unique=True)
    u_password = models.CharField(max_length=256)
    u_email = models.CharField(max_length=64, unique=True)
    u_icon = models.ImageField(upload_to='icons/%Y/%m/%d/')
    is_active = models.BooleanField(default=False)
    is_delete = models.BooleanField(default=False)

    class Meta:
        db_table = 'axf_user'


class Cart(models.Model):
    c_user = models.ForeignKey(AXFUser)
    c_goods = models.ForeignKey(Goods)
    c_goods_num = models.IntegerField(default=1)
    c_is_select = models.BooleanField(default=True)

    class Meta:
        db_table = 'axf_cart'


class Order(models.Model):
    o_user = models.ForeignKey(AXFUser)
    o_price = models.FloatField(default=0)
    o_time = models.DateTimeField(auto_now=True)
    o_status = models.IntegerField(default=ORDER_STATUS_NOT_PAY)

    class Meta:
        db_table = 'axf_order'


class OrderGoods(models.Model):
    o_order = models.ForeignKey(Order)
    o_goods = models.ForeignKey(Goods)
    o_goods_num = models.IntegerField(default=1)

    class Meta:
        db_table = 'axf_ordergoods'

templates/order/order_detail.html
{% extends 'base_order.html' %}
{% load static %}

{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/order/css/order_detail.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/order/js/order_detail.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="order_detail" class="container">
        <h6>订单编号:{{ order.id }}</h6>
        <ul>
            {% for ordergoods in order.ordergoods_set.all %}
                <li class="menuList">
                    <a href="#">
                        <img src="{{ ordergoods.o_goods.productimg }}" alt="{{ ordergoods.o_goods.productlongname }}">
                        <p>{{ ordergoods.o_goods.productlongname }}</p>
                        <p class="presentPrice">{{ ordergoods.o_goods.price }}</p>
                    </a>
                    <section>
                        <span>{{ ordergoods.o_goods_num }}</span>
                    </section>
                </li>
            {% endfor %}
        </ul>
        <h6 class="total_price">总价:&nbsp;<span id="total_price">{{ order.o_price }}</span></h6>
        <button orderid="{{ order.id }}" id="alipay" class="btn btn-success btn-block">支付</button>
    </div>
{% endblock %}

templates/order/order_list_not_pay.html
{% extends 'base_order.html' %}
{% load static %}
{% block ext_css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/order/css/order_list_not_pay.css' %}">
{% endblock %}

{% block ext_js %}
    {{ block.super }}
    <script type="text/javascript" src="{% static 'axf/order/js/order_list_not_pay.js' %}"></script>
{% endblock %}

{% block content %}
    <div id="order_list_not_pay" class="container">
        <ol>
            {% for order in orders %}
                <li>
                    <ul class="order" orderid="{{ order.id }}">
                        <h6>订单编号:{{ order.id }}</h6>
                        {% for ordergoods in order.ordergoods_set.all %}
                            <li class="menuList">
                                <a href="#">
                                    <img src="{{ ordergoods.o_goods.productimg }}" alt="{{ ordergoods.o_goods.productlongname }}">
                                    <p>{{ ordergoods.o_goods.productlongname }}</p>
                                    <p class="presentPrice">{{ ordergoods.o_goods.price }}</p>
                                </a>
                                <section>
                                    <span>{{ ordergoods.o_goods_num }}</span>
                                </section>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ol>
    </div>
{% endblock %}